// Autogenerated code by https://app.quicktype.io/.

// To parse this data:
//
//   import { Convert, ClientInfo } from "./file";
//
//   const clientInfo = Convert.toClientInfo(json);
//
// These functions will throw an error if the JSON doesn't
// match the expected interface, even if the JSON is valid.

export interface ClientInfo {
    clientId?:    string;
    name?:        string;
    webHookUrl?:  string;
    permissions?: string;
    accounts?:    Account[];
    jars?:        Jar[];
}

export interface Account {
    id?:           string;
    sendId?:       string;
    balance?:      number;
    creditLimit?:  number;
    type?:         string;
    currencyCode?: number;
    cashbackType?: string;
    maskedPan?:    string[];
    iban?:         string;
}

export interface Jar {
    id?:           string;
    sendId?:       string;
    title?:        string;
    description?:  string;
    currencyCode?: number;
    balance?:      number;
    goal?:         number;
}

// Converts JSON strings to/from your types
// and asserts the results of JSON.parse at runtime
export class Convert {
    public static toClientInfo(json: string): ClientInfo {
        return cast(JSON.parse(json), r("ClientInfo"));
    }

    public static clientInfoToJson(value: ClientInfo): string {
        return JSON.stringify(uncast(value, r("ClientInfo")), null, 2);
    }
}

function invalidValue(typ: any, val: any, key: any = ''): never {
    if (key) {
        throw Error(`Invalid value for key "${key}". Expected type ${JSON.stringify(typ)} but got ${JSON.stringify(val)}`);
    }
    throw Error(`Invalid value ${JSON.stringify(val)} for type ${JSON.stringify(typ)}`, );
}

function jsonToJSProps(typ: any): any {
    if (typ.jsonToJS === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.json] = { key: p.js, typ: p.typ });
        typ.jsonToJS = map;
    }
    return typ.jsonToJS;
}

function jsToJSONProps(typ: any): any {
    if (typ.jsToJSON === undefined) {
        const map: any = {};
        typ.props.forEach((p: any) => map[p.js] = { key: p.json, typ: p.typ });
        typ.jsToJSON = map;
    }
    return typ.jsToJSON;
}

function transform(val: any, typ: any, getProps: any, key: any = ''): any {
    function transformPrimitive(typ: string, val: any): any {
        if (typeof typ === typeof val) return val;
        return invalidValue(typ, val, key);
    }

    function transformUnion(typs: any[], val: any): any {
        // val must validate against one typ in typs
        const l = typs.length;
        for (let i = 0; i < l; i++) {
            const typ = typs[i];
            try {
                return transform(val, typ, getProps);
            } catch (_) {}
        }
        return invalidValue(typs, val);
    }

    function transformEnum(cases: string[], val: any): any {
        if (cases.indexOf(val) !== -1) return val;
        return invalidValue(cases, val);
    }

    function transformArray(typ: any, val: any): any {
        // val must be an array with no invalid elements
        if (!Array.isArray(val)) return invalidValue("array", val);
        return val.map(el => transform(el, typ, getProps));
    }

    function transformDate(val: any): any {
        if (val === null) {
            return null;
        }
        const d = new Date(val);
        if (isNaN(d.valueOf())) {
            return invalidValue("Date", val);
        }
        return d;
    }

    function transformObject(props: { [k: string]: any }, additional: any, val: any): any {
        if (val === null || typeof val !== "object" || Array.isArray(val)) {
            return invalidValue("object", val);
        }
        const result: any = {};
        Object.getOwnPropertyNames(props).forEach(key => {
            const prop = props[key];
            const v = Object.prototype.hasOwnProperty.call(val, key) ? val[key] : undefined;
            result[prop.key] = transform(v, prop.typ, getProps, prop.key);
        });
        Object.getOwnPropertyNames(val).forEach(key => {
            if (!Object.prototype.hasOwnProperty.call(props, key)) {
                result[key] = transform(val[key], additional, getProps, key);
            }
        });
        return result;
    }

    if (typ === "any") return val;
    if (typ === null) {
        if (val === null) return val;
        return invalidValue(typ, val);
    }
    if (typ === false) return invalidValue(typ, val);
    while (typeof typ === "object" && typ.ref !== undefined) {
        typ = typeMap[typ.ref];
    }
    if (Array.isArray(typ)) return transformEnum(typ, val);
    if (typeof typ === "object") {
        return typ.hasOwnProperty("unionMembers") ? transformUnion(typ.unionMembers, val)
            : typ.hasOwnProperty("arrayItems")    ? transformArray(typ.arrayItems, val)
            : typ.hasOwnProperty("props")         ? transformObject(getProps(typ), typ.additional, val)
            : invalidValue(typ, val);
    }
    // Numbers can be parsed by Date but shouldn't be.
    if (typ === Date && typeof val !== "number") return transformDate(val);
    return transformPrimitive(typ, val);
}

function cast<T>(val: any, typ: any): T {
    return transform(val, typ, jsonToJSProps);
}

function uncast<T>(val: T, typ: any): any {
    return transform(val, typ, jsToJSONProps);
}

function a(typ: any) {
    return { arrayItems: typ };
}

function u(...typs: any[]) {
    return { unionMembers: typs };
}

function o(props: any[], additional: any) {
    return { props, additional };
}

function m(additional: any) {
    return { props: [], additional };
}

function r(name: string) {
    return { ref: name };
}

const typeMap: any = {
    "ClientInfo": o([
        { json: "clientId", js: "clientId", typ: u(undefined, "") },
        { json: "name", js: "name", typ: u(undefined, "") },
        { json: "webHookUrl", js: "webHookUrl", typ: u(undefined, "") },
        { json: "permissions", js: "permissions", typ: u(undefined, "") },
        { json: "accounts", js: "accounts", typ: u(undefined, a(r("Account"))) },
        { json: "jars", js: "jars", typ: u(undefined, a(r("Jar"))) },
    ], false),
    "Account": o([
        { json: "id", js: "id", typ: u(undefined, "") },
        { json: "sendId", js: "sendId", typ: u(undefined, "") },
        { json: "balance", js: "balance", typ: u(undefined, 0) },
        { json: "creditLimit", js: "creditLimit", typ: u(undefined, 0) },
        { json: "type", js: "type", typ: u(undefined, "") },
        { json: "currencyCode", js: "currencyCode", typ: u(undefined, 0) },
        { json: "cashbackType", js: "cashbackType", typ: u(undefined, "") },
        { json: "maskedPan", js: "maskedPan", typ: u(undefined, a("")) },
        { json: "iban", js: "iban", typ: u(undefined, "") },
    ], false),
    "Jar": o([
        { json: "id", js: "id", typ: u(undefined, "") },
        { json: "sendId", js: "sendId", typ: u(undefined, "") },
        { json: "title", js: "title", typ: u(undefined, "") },
        { json: "description", js: "description", typ: u(undefined, "") },
        { json: "currencyCode", js: "currencyCode", typ: u(undefined, 0) },
        { json: "balance", js: "balance", typ: u(undefined, 0) },
        { json: "goal", js: "goal", typ: u(undefined, 0) },
    ], false),
};
